<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="UnifieChat brings every customer conversation into one simple inbox.">
    <title>UnifieChat — One inbox for every customer message</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-ink text-white antialiased">
    <div class="page-glow" aria-hidden="true"></div>
    <header class="site-header"><div class="shell header-inner"><a class="brand" href="#top" aria-label="UnifieChat home"><span class="brand-mark">U</span><span>UnifieChat</span></a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" data-menu-toggle><span></span><span></span><span></span></button><nav class="main-nav" data-menu><a href="#channels">Channels</a><a href="#features">Solutions</a><a href="#audience">Who it’s for</a><a href="#faq">FAQ</a><a class="nav-cta" href="#waitlist">Start Free Trial <span>↗</span></a></nav></div></header>
    <main id="top">
        <section class="hero shell"><div class="eyebrow"><span class="eyebrow-dot"></span> One inbox for every customer message</div><h1>Your customers are talking.<br><em>Don’t miss the conversation.</em></h1><p class="hero-copy">Stop jumping between WhatsApp, Instagram, Facebook, X, TikTok and more. Bring every conversation into one simple dashboard, respond faster, and keep every interaction organized.</p><div class="hero-actions"><a class="button button-primary" href="#waitlist">Start free trial <span>↗</span></a><a class="button button-secondary" href="#waitlist">Book a Demo Session <span>↗</span></a></div><div class="inbox-window" aria-label="Preview of the unified inbox"><div class="window-top"><div class="window-dots"><i></i><i></i><i></i></div><span>UnifieChat inbox</span><span class="window-date">Today <b>⌄</b></span></div><div class="inbox-layout"><aside class="inbox-sidebar"><strong>Inbox</strong><a class="side-link active" href="#"><span>◉</span> All inbox <b>8</b></a><a class="side-link" href="#"><span class="channel-icon whatsapp">◔</span> WhatsApp <b>3</b></a><a class="side-link" href="#"><span class="channel-icon instagram">◎</span> Instagram <b>2</b></a><a class="side-link" href="#"><span class="channel-icon facebook">f</span> Facebook <b>2</b></a><a class="side-link" href="#"><span class="channel-icon telegram">➤</span> Telegram <b>1</b></a><a class="side-link" href="#"><span class="channel-icon x-icon">𝕏</span> X</a><div class="sidebar-bottom"><span>⚙</span> Settings</div></aside><div class="conversation-list"><div class="list-heading"><strong>All conversations</strong><span>⌕</span></div><div class="conversation selected"><span class="avatar avatar-orange">AE</span><div><strong>Amaka Eze</strong><small>Hi! Is the blue ankara...</small></div><i class="unread">2</i></div><div class="conversation"><span class="avatar avatar-purple">TB</span><div><strong>Tunde Bakare</strong><small>Saw your reel. Do you...</small></div><i class="unread">1</i></div><div class="conversation"><span class="avatar avatar-green">GM</span><div><strong>Grace Mensah</strong><small>Can I move my appoint...</small></div><time>10:42</time></div><div class="conversation"><span class="avatar avatar-blue">KO</span><div><strong>Kelechi Obi</strong><small>Payment sent, thank you!</small></div><time>09:18</time></div></div><div class="chat-panel"><div class="chat-header"><div><strong>Amaka Eze</strong><small><span class="online-dot"></span> WhatsApp · Online</small></div><span>⋯</span></div><div class="chat-body"><div class="message received">Hi! Is the blue ankara set still available in size M?<small>10:51 AM</small></div><div class="message sent">Hi Amaka! Yes, it is available. I’ll reserve one for you. 😊<small>10:52 AM</small></div></div><div class="chat-input"><span>Reply without switching apps…</span><button type="button">↑</button></div></div></div></div><p class="scroll-note">Business moves fast. Your replies should too. <span>↓</span></p></section>
        <section class="section shell" id="solutions"><div class="section-intro"><div class="eyebrow">Your business. Your customers. One inbox.</div><h2>Know who messaged, who needs a reply, and who’s waiting.</h2><p>Running a small business already means doing a lot. Stop switching apps just to find out who messaged you.</p></div><div class="feature-row"><article class="mini-card"><span class="card-icon">◉</span><h3>See Every Message</h3><p>A unified view of conversations across your connected channels at a glance.</p></article><article class="mini-card"><span class="card-icon coral">♢</span><h3>Never Miss a Notification</h3><p>New messages, mentions, replies and key interactions all in one place.</p></article><article class="mini-card"><span class="card-icon purple">↗</span><h3>Reply Without Switching Apps</h3><p>Respond from your dashboard in a minute instead of opening multiple platforms.</p></article><article class="mini-card"><span class="card-icon gold">▣</span><h3>Stay Organized</h3><p>Spot unread, pending and resolved conversations at a glance.</p></article></div></section>
        <section class="section shell" id="channels"><div class="section-intro"><div class="eyebrow">Channels</div><h2>Stop checking five apps to answer one customer.</h2><p>Your customers expect a swift response. Meet them wherever they reach out.</p></div><div class="tabs" data-tabs><button class="tab active" data-tab="whatsapp">WhatsApp</button><button class="tab" data-tab="instagram">Instagram</button><button class="tab" data-tab="facebook">Facebook</button><button class="tab" data-tab="more">More channels</button></div><div class="channel-panel"><div class="channel-panel-icon whatsapp">◔</div><div><h3 data-channel-title>WhatsApp</h3><p data-channel-copy>Customer questions, orders, support requests, and follow-ups.</p></div><span class="panel-arrow">↗</span></div></section>
        <section class="section shell" id="features"><div class="section-intro"><div class="eyebrow">Features</div><h2>Everything you need to stay on top of customer conversations.</h2></div><div class="feature-grid"><article class="feature-card"><span>▣</span><h3>Unified Inbox</h3><p>Conversations from your connected platforms in one centralized inbox.</p></article><article class="feature-card"><span>♢</span><h3>Smart Notifications</h3><p>Know when a customer messages, replies, mentions you, or needs attention.</p></article><article class="feature-card"><span>↗</span><h3>Fast Replies</h3><p>Read and respond without constantly switching applications.</p></article><article class="feature-card"><span>⌕</span><h3>Search Conversations</h3><p>Find previous conversations quickly when you need context.</p></article><article class="feature-card"><span>◉</span><h3>Customer Context</h3><p>See who you’re talking to and their history before replying.</p></article><article class="feature-card"><span>✓</span><h3>Conversation Status</h3><p>Track what’s new, ongoing, waiting for a response, or resolved.</p></article><article class="feature-card"><span>♧</span><h3>Team Inbox</h3><p>One place for your team to manage communication and avoid duplicate replies.</p></article></div></section>
        <section class="section shell" id="audience"><div class="section-intro"><div class="eyebrow">Who it’s for</div><h2>Your customers are already messaging you.</h2><p>Stay responsive without adding more complexity to your day.</p></div><div class="audience-tabs"><button class="audience-tab active">Retail</button><button class="audience-tab">Services</button><button class="audience-tab">Restaurants</button><button class="audience-tab">Online Businesses</button><button class="audience-tab">Growing Teams</button></div><div class="audience-panel"><div><h3>Retail</h3><p>Manage product enquiries, orders, availability questions, and customer follow-ups.</p></div><span>→</span></div></section>
        <section class="section shell comparison"><div class="section-intro"><div class="eyebrow">Less switching. Faster replies. Happier customers.</div><h2>See the difference.</h2></div><div class="toggle" data-comparison><button class="active" data-view="without">Without UnifieChat</button><button data-view="with">With UnifieChat</button></div><div class="comparison-card"><ul class="comparison-list"><li>Constantly switching between apps</li><li>Missing customer messages</li><li>Forgetting to reply</li><li>Losing track of conversations</li><li>Checking notifications manually</li><li>Multiple people responding to the same customer</li></ul></div></section>
        <section class="section shell faq-section" id="faq"><div class="section-intro centered"><h2>Frequently asked questions</h2></div><div class="faq-list"><details open><summary>What is UnifieChat?<span>+</span></summary><p>A customer communication platform that helps small and medium-sized businesses manage messages and notifications from multiple channels in one place.</p></details><details><summary>Who is it for?<span>+</span></summary><p>Primarily SMEs that receive enquiries, orders, bookings, support requests and other messages through social and messaging platforms.</p></details><details><summary>Can I reply to customers from the platform?<span>+</span></summary><p>Yes. The goal is to let you read and respond without constantly switching between applications.</p></details><details><summary>Can my team use it?<span>+</span></summary><p>Yes. A shared inbox helps team members manage conversations and coordinate responses.</p></details><details><summary>Will I still receive notifications from my existing platforms?<span>+</span></summary><p>It’s designed to centralize relevant customer notifications and conversations so you can manage them from one dashboard.</p></details><details><summary>Do I need technical knowledge?<span>+</span></summary><p>No. It’s simple enough for a business owner or team member to start using without technical expertise.</p></details></div></section>
        <section class="cta shell" id="waitlist"><div><div class="eyebrow">Stay in the loop</div><h2>Are you seeing every message?</h2><p>Your customers are already reaching out. Connect. See. Reply. Grow.</p></div><form class="waitlist-form" data-waitlist><label class="sr-only" for="email">Business email</label><input id="email" name="email" type="email" placeholder="you@business.com" required><button class="button button-light" type="submit">Join the Waitlist <span>↗</span></button><small data-form-message></small></form></section>
    </main>
    <footer class="site-footer shell"><a class="brand" href="#top"><span class="brand-mark">U</span><span>UnifieChat</span></a><div class="socials"><a href="#" aria-label="Instagram">◎</a><a href="#" aria-label="TikTok">♪</a><a href="#" aria-label="WhatsApp">◔</a><a href="#" aria-label="Facebook">f</a><a href="#" aria-label="X">𝕏</a></div><p>© 2026 UnifieChat. All rights reserved.</p></footer>
</body>
</html>
